# Generated by Django 5.0.4 on 2024-05-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('idHorario', models.IntegerField()),
                ('Hora_Entrada', models.DateTimeField()),
                ('Hora_Salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
