# Generated by Django 5.0.4 on 2024-05-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_Salon',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('idMaestro', models.IntegerField()),
                ('idMateria', models.IntegerField()),
                ('idSalon', models.IntegerField()),
                ('Numero_Alumnos', models.IntegerField()),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fecha_Fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'horario_salon',
            },
        ),
    ]
