# Generated by Django 5.0.4 on 2024-05-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('idmaestro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
    ]
