# Generated by Django 5.0.4 on 2024-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('idSalon', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'salon',
            },
        ),
    ]
